spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      routes:
        - id: tasks-microservice
          uri: lb://tasks-microservice
          predicates:
            - Path=/api/tasks/**
        - id: users-microservice
          uri: lb://users-microservice
          predicates:
            - Path=/api/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080
